### ISSUE TITLE
global name 'CalledProcessError' is not defined

### ISSUE THREAD

**Issue by virtualjj** [alestic/aws-lambda-codepipeline-site-generator-hugo#4]
I'm new to Lambda and Hugo so bear with me please. I'm not sure if I'm having an issue with this plugin or [aws-git-backed-static-website](https://github.com/alestic/aws-git-backed-static-website).  I'm suspecting user error but here are the commands that I used to setup Hugo and commit to the CodeCommit repo that is created by the aws-git-backed-static-website CloudFormation template.

On my local OS X box I ran the following commands:

```
hugo new site <my domain name>
cd <my domain name>
mkdir themes
cd themes/
git clone https://github.com/halogenica/Hugo-BeautifulHugo.git beautifulhugo
cd ..
git init
git config --local user.name "<My Name>"
for DIR in `ls -p | grep /`; do touch ${DIR}.gitkeep; done
echo "public" >> .gitignore
```
Use this command to make sure I can connect to the CodeCommit repository that was created:

`ssh -A <My CodeCommit SSH ID>@git-codecommit.us-east-1.amazonaws.com`

Add the CodeCommit origin:

`git remote add origin ssh://<My CodeCommit SSH ID>@git-codecommit.us-east-1.amazonaws.com/v1/repos/<My Domain Name>`

Add the Hugo site and commit:

```
git add .
git commit -m "First commit."
git push origin master
```
The push hits the CodeCommit repo but the site is never deployed and I see the following logs in CloudWatch:

When using `--theme <theme name>` for **GeneratorLambdaFunctionUserParameters**:

```
['./hugo', '--source=/tmp/tmpjdVl7j', '--destination=/tmp/tmpNveKmN', '--theme', 'beautifulhugo']
global name 'CalledProcessError' is not defined
Traceback (most recent call last):
File "/var/task/index.py", line 78, in handler
generate_static_site(source_dir, site_dir, user_parameters)
File "/var/task/index.py", line 106, in generate_static_site
except CalledProcessError as e:
NameError: global name 'CalledProcessError' is not defined
Parameter validation failed: Invalid type for parameter failureDetails.message, value: global name 'CalledProcessError' is not defined, type: <type 'exceptions.NameError'>, valid types: <type 'basestring'>: ParamValidationError Traceback (most recent call last): File "/var/task/index.py", line 90, in handler code_pipeline.put_job_failure_result(jobId=job_id, failureDetails={'message': e, 'type': 'JobFailed'}) File "/var/runtime/botocore/client.py", line 251, in _api_call return self._make_api_call(operation_name, kwargs) File "/var/runtime/botocore/client.py", line 513, in _make_api_call api_params, operation_model, context=request_context) File "/var/runtime/botocore/client.py", line 566, in _convert_to_request_dict api_params, operation_model) File "/var/runtime/botocore/validate.py", line 270, in serialize_to_request raise ParamValidationError(report=report.generate_report()) ParamValidationError: Parameter validation failed: Invalid type for parameter failureDetails.message, value: global name 'CalledProcessError' is not defined, type: <type 'exceptions.NameError'>, valid types: <type 'basestring'>
```
I tried taking out the **GeneratorLambdaFunctionUserParameters** parameter and got the following error:

```
File "/var/task/index.py", line 68, in handler
to_bucket, to_key, user_parameters) = setup(event)
File "/var/task/index.py", line 38, in setup
user_parameters = config['UserParameters']
KeyError: 'UserParameters'
local variable 'source_dir' referenced before assignment: UnboundLocalError
Traceback (most recent call last):
File "/var/task/index.py", line 93, in handler
shutil.rmtree(source_dir)
UnboundLocalError: local variable 'source_dir' referenced before assignment
```
I then tried using `--theme=<theme name>` for **GeneratorLambdaFunctionUserParameters**:

`NameError: global name 'CalledProcessError' is not defined`

When I launched the CloudFormation stack I used the following settings:

![image](https://cloud.githubusercontent.com/assets/10323889/21564647/0aa19e26-ced3-11e6-9987-490718088102.png)

Here is the message that I get when I open the site by domain name:

![image](https://cloud.githubusercontent.com/assets/10323889/21564922/dc8d9ccc-ced4-11e6-8793-94bfb8ca0b30.png)

**Comment by ehammond** [comment]
@virtualjj: Excellent problem report, thanks! 

I don't have an immediate answer, but have a couple ideas and will look into it.

**Comment by ehammond** [comment]
@virtualjj:

The first Google search result for the error was (of course) a StackOverflow question and the answers provided solutions to get around our first hurdle: http://stackoverflow.com/questions/25058834/failing-to-catch-a-specific-error

If you update the AWS Lambda function code (run the stack again) you should now see the specific hugo error in the CloudWatch logs. You can upload this ZIP file in the AWS Lambda console: https://s3.amazonaws.com/run.alestic.com/lambda/aws-lambda-site-generator-hugo.zip

I'm also going to make a prediction that the problem you are experiencing is because the content of your hugo themes/ subdirectory is not committed to your CodeCommit repository. That repo needs to have *all* of the files necessary to build the static site with hugo.

Thanks again for a clear problem report.
